name: Release
"on":
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: <role_name> #TODO: Set role name

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3.2.0
        with:
          path: <role_name> #TODO: Set role name

      - name: Set up Python 3.
        uses: actions/setup-python@v4.4.0
        with:
          python-version: "3.x"

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          ${{ github.repository_owner }} $(echo ${{ github.repository }} | cut -d/ -f2)
